disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "ko8-zzz Notes"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/nav_icon42.svg"
author = { name = "Tomohiro Kobayashi", headline = "Hi!", bio = "test" }
description = "test"
secondaryLogo = "icon.png"
