[[main]]
name = "Posts"
pageRef = "posts"
identifier = "zI2vvnX6nL"
weight = 9999

# [[main]]
# name = "Bio"
# pageRef = "profiles"
# identifier = "zh2vanX6nL"
# weight = 9999

[[footer]]
none = "none"