[[main]]
name = "Posts"
pageRef = "posts"
identifier = "zI2vvnX6nL"
weight = 2

[[main]]
name = "Profile"
pageRef = "profile"
identifier = "zhfdnX6nL"
weight = 1

[[main]]
name = "Tags"
pageRef = "tags"
identifier = "few8fsda"
weight = 3

[[footer]]
none = "none"